linters:
  disable-all: true
  enable:
    - deadcode
    - depguard
    - dupl
    - errcheck
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - maligned
    - megacheck
    - misspell
    - nakedret
    - prealloc
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck

linters-settings:
  depguard:
    rules:
      main:
        allow:
          - github.com/QuinMD/helm-s3-proxy/internal/handler
          - github.com/aws/aws-sdk-go/aws/session
          - github.com/aws/aws-sdk-go/service/s3/s3manager
          - github.com/aws/aws-sdk-go/service/sts
          - github.com/cresta/gotracing
          - github.com/cresta/gotracing/datadog
          - github.com/cresta/httpsimple
          - github.com/cresta/zapctx
          - github.com/gorilla/mux
