name: Release Charts

on:
  push:
    paths:
      - charts/**
      - .github/workflows/helm.yml
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.7.2
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1
      - name: Run chart-testing (lint)
        run: ct lint --all
      - name: Create kind cluster
        uses: helm/kind-action@v1.10.0
      - name: Helm package
        run: helm package charts/helm-s3-proxy --destination .
      - name: Run install
        run: helm install helm-s3-proxy *.tgz
      - name: Remove helm chart
        run:  helm uninstall helm-s3-proxy
  release:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.7.1
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

