name: Release Charts

on:
  push:
    paths:
      - charts/**
      - .github/workflows/helm.yml
    branches:
      - main
      - helm-chart-updates

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.7.2
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1
      - name: Run chart-testing (lint)
        run: helm lint charts/helm-s3-proxy
      - name: Create kind cluster
        uses: helm/kind-action@v1.10.0
      - name: Helm package
        run: helm package charts/helm-s3-proxy
      - name: Run install
        run: helm install helm-s3-proxy helm-s3-proxy.tgz
      - name: Remove helm chart
        run:  helm uninstall helm-s3-proxy
  release:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Helm package
        run: helm package charts/helm-s3-proxy
      - name: Log into GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push chart to GHCR
        run: helm push ./helm-s3-proxy.tgz oci://ghcr.io/quinmd/charts/helm-s3-proxy

